### ISSUE TITLE
tmk developer workflow

### ISSUE THREAD

**Issue by wobbol** [ErgoDox/tmk_ErgoDox#19]
if we have a developer that wants to use their ErgoDox to develop tmk_core with our repo, what is the recommended workflow?

@marknsikora I think this is a question best answered by you

**Comment by marknsikora** [comment]
A little complicated due to the nature of submodules. But I would probably say something like
1. Fork your own copy of tmk
2. Clone a new copy of this repo without syncing submodules
3. Modify the gitsubmodules to point to your tmk fork
4. Sync submodules

At that point the folder with tmk will work like it's own git repo and changes can be pushed to the users fork
